### PR TITLE
Support escaped dollar signs and open braces

### PR DESCRIPTION
**Pull request by NoxHarmonium**
This PR contains a fix for #96

I have tested it by pulling it into the project that I was having the issue on and checking that it fixes the problem.

Let me know if I need to do anything else to get this PR into a position where it can be merged.

### CODE REVIEW

**Comment by adrianjost** [comment]
Thank you very much for your contribution @NoxHarmonium. Unfortunately I have overseen your PR for quite a while but will take a look into it at the weekend.
But let's clarify first, that I fully understand your issue. The issue you had is, that dedent evaluated the template string expression instead of keeping it as is? For Example
```
const a = "hi"
console.log(dedent("good morning and ${a}"))
``
logged `"good morning and hi"` instead of `"good morning and ${a}"`, right?

**Comment by NoxHarmonium** [comment]
No worries! Thanks for spending the time to maintain such a handy library,

My issue is actually when I'm using template strings.

If you want to avoid `${expression}` from being evaluated in a template string you can escape it with a forward slash.

E.g.))
```
console.log(dedent`\${pleaseDontEvaluateThis}`);

// Expected: "${pleaseDontEvaluateThis}"
// Actual: "\${pleaseDontEvaluateThis}"
```

From: https://hacks.mozilla.org/2015/05/es6-in-depth-template-strings-2/

> Likewise, if you need to include the two characters ${ in a template string, I don’t want to know what you’re up to, but you can escape either character with a backslash: `write \${ or $\{`.

Dedent was keeping the slash in front of the dollar sign instead of interpreting it as an escape character.

Actually, as I am writing this I just realised that the reason we need all these find and replace for escape characters is dedent uses the `raw` property. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Raw_strings

> The special raw property, available on the first argument to the tag function, allows you to access the raw strings as they were entered, without processing escape sequences.

I wonder if we could use a string that already has escape characters processed to avoid all these find and replace statements. :thinking: 

I'll have a play this weekend too.

**Comment by adrianjost** [comment]
Ahh now I understand. My first intuition is that the issue comes from `.raw` (as you just said as well). I have the feeling that we could prevent those issues if we remove the `.raw`.
Cause I haven't written this library myself and just added some new features to it, I am wondering why `.raw` was used in the first place. Will take a look into this! :) I think as long as all other tests are still running we should be fine changing it :)

**Comment by adrianjost** [comment]
I've looked a bit more closely on your pr and I think you are somehow on a good way. Escaping `$` or `{` are the only options to skip the evaluation of templates within a template string. 

However I am wondering why you need to do this in the first place. If you don't want't the template to be evaluated why can't you just use a regular string instead? Then you wouldn't need to escape anything and it should work.

More learning I got:
Dedent needs to use `.raw` to detect explicit newslines. Without `.raw` those would be indistinguishable from regular newlines. For that reason we can't simply change this.

All in all I wasn't able to come up with any test case that would break by your changes. So I am confident that we can merge this. But I would prefer to think a bit more about this, just in case we overlook something. I am especially concerned that we break something for normal strings.

**Comment by NoxHarmonium** [comment]
> However I am wondering why you need to do this in the first place. If you don't want't the template to be evaluated why can't you just use a regular string instead? Then you wouldn't need to escape anything and it should work.

We are using dedent as a simple way to generate blocks of SQL based on JSON schemas in our build pipeline. I can't share the code but we have functions that generate blocks of SQL that look something like:

```typescript
const generateCreateTableBlock = (tableName: string, columnsDefinitions: string) => dedent`
   CREATE OR REPLACE TABLE ${tableName}
     ${columnDefinitions};
`;
```
Although in the real project the blocks are usually a lot larger so `dedent` allows us to write the multi-line templates. Using a regular string would mean that we couldn't span multiple lines and write these templates in a readable way.

This template system has grown pretty large and generates about 4000 lines of SQL. It worked great until recently when we needed to generate [Snowflake stored procedures](https://docs.snowflake.com/en/sql-reference/stored-procedures.html) that are written in Javascript. Inside these stored procedures we wanted to use template strings. So we ended up with a function kind of like this:

```typescript
 dedent`
    CREATE OR REPLACE PROCEDURE ${procedureName}()
      RETURNS STRING
      LANGUAGE JAVASCRIPT      
      COMMENT = 'Contrived stored procedure to demonstrate escaped template strings'
    AS $$
    const statement = snowflake.createStatement(
       {
         sqlText: "INSERT INTO table2 (col1, col2) VALUES (?, ?);",
         binds:["LiteralValue1", variable2]
      }
    );
   
    const queryId = statement.getQueryId();
    return \`Query ID is: [\$\{queryId}]\`;
    $$;
`;
```
`dedent` then started printing the escape characters with the slash in the generated SQL so Snowflake wouldn't accept it. So we created the fork.

> Dedent needs to use .raw to detect explicit newslines. Without .raw those would be indistinguishable from regular newlines. For that reason we can't simply change this.

That makes a lot of sense! Annoying that we can't use the native escape character handling but it seems unavoidable here.

FWIW we have been using this fork in our production build pipeline for a few weeks now with no issues and we use `dedent` pretty extensively. However, I get that it is a big responsibility merging code that could break existing users in such a widely used library. I'm happy to write some more tests if it will make you feel more confident. Maybe we could construct a test case with a mix of all the escape characters currently supported by dedent.

I wonder if we are missing other escape characters as well. Maybe we could take a look at something like https://github.com/iansan5653/unraw/blob/master/src/index.ts for inspiration, although it doesn't seem to handle template strings and it is probably better to get this merged in and open another issue for the other escape characters so we don't get scope creep.

Let me know what you think!

**Comment by adrianjost** [comment]
Thank you for the in depth explanation of your use case.

After thinking about it a bit more I think the best solution would be to unescape all characters so that dedent behaves the same for regular string as well as template strings. But I agree that this is out of scope of this PR.
I also noticed, that dedent does not even have tests for the simple function usage with regular strings. I will definitely add those in the near future.
But I am loosing focus again...

To merge this PR, I request you to:
- [ ] add the new behaviour to the README file, so it's clearly communicated that dedent does unescape certain characters but not all. In my opinion it's ok to have this odd behaviour for some time if it's well documented.
- [ ] add a test that checks that dedent behaves the same for regular and template strings for the newly added characters
```
dd`\$\{Hi}` === dd("\$\{Hi}"))
```

After that is done, I am happy to merge this PR. 🚀

**Comment by NoxHarmonium** [comment]
Sure, I'll get those changes done before the end of the week.

**Comment by NoxHarmonium** [comment]
@adrianjost I've pushed up the requested changes. Ready for review!

**Review by adrianjost — APPROVED** [review]
That's perfect. Thanks 🚀

**Comment by adrianjost** [comment]
I will release this later this week.

**Pull request merged**
