### PR TITLE
fix types

### PR DESCRIPTION
**Pull request by SuperchupuDev**
Turns out #375 had inacurrate types, whoops!

This PR marks the `dedent` function as a default export, and uses the `export =` CJS module syntax, just like how it was before on `@types/dedent-tabs`

### CODE REVIEW

**Comment by SuperchupuDev** [comment]
hey @adrianjost, it's been a little over 2 months since i made this pr, i think you overlooked it? the types from my old PR aren't accurate at all, it would be really nice to have this fix landing sometime soon

**Comment by adrianjost** [comment]
Oh yes, definitely overlooked this. I get so many PRs each day. I'm very sorry. I will put it on my list to look at this soon. Thanks for bringing this up again. 💚

**Review by adrianjost — APPROVED** [review]

**Comment by SuperchupuDev** [comment]
hello again @adrianjost, it's been a while since this PR was merged, can we get a release with the fix anytime soon?

**Comment by adrianjost** [comment]
v0.10.3 is now released. Sorry for the delay!
https://www.npmjs.com/package/dedent-tabs/v/0.10.3

**Pull request merged**
